data={
"corG-1":{"seq":1,"level":1,"module":"cor","term":"accountingEntries","code":""},
"corG-2":{"seq":2,"level":2,"module":"cor","term":"documentInfo","code":""},
"cor-76":{"seq":373,"level":3,"module":"cor","term":"documentNumber","code":"BT-1"},
"cor-79":{"seq":376,"level":3,"module":"cor","term":"documentDate","code":"BT-2"},
"cor-73":{"seq":370,"level":3,"module":"cor","term":"documentType","code":"BT-3"},
"muc-4":{"seq":324,"level":3,"module":"muc","term":"amountOriginalCurrency","code":"BT-5"},
"cor-43":{"seq":338,"level":3,"module":"cor","term":"postingDate","code":"BT-7"},
"cen-8":{"seq":287,"level":3,"module":"cen","term":"ValueAddedTaxPointDateCode","code":"BT-8"},
"cenG-16":{"seq":24,"level":3,"module":"cen","term":"PAYMENT_INSTRUCTIONS","code":"BG-16"},
"cen-82":{"seq":25,"level":4,"module":"cen","term":"PaymentMeansText","code":"BT-82"},
"cen-83":{"seq":26,"level":4,"module":"cen","term":"RemittanceInformation","code":"BT-83"},
"cenG-17":{"seq":27,"level":4,"module":"cen","term":"CREDIT_TRANSFER","code":"BG-17"},
"cen-84":{"seq":28,"level":5,"module":"cen","term":"PaymentAccountIdentifier","code":"BT-84"},
"cen-85":{"seq":29,"level":5,"module":"cen","term":"PaymentAccountName","code":"BT-85"},
"cen-86":{"seq":30,"level":5,"module":"cen","term":"PaymentServiceProviderIdentifier","code":"BT-86"},
"cenG-18":{"seq":31,"level":4,"module":"cen","term":"PAYMENT_CARD_INFORMATION","code":"BG-18"},
"cen-87":{"seq":32,"level":5,"module":"cen","term":"PaymentCardPrimaryAccountNumber","code":"BT-87"},
"cen-88":{"seq":33,"level":5,"module":"cen","term":"PaymentCardHolderName","code":"BT-88"},
"cenG-19":{"seq":34,"level":4,"module":"cen","term":"DIRECT_DEBIT","code":"BG-19"},
"cen-89":{"seq":35,"level":5,"module":"cen","term":"MandateReferenceIdentifier","code":"BT-89"},
"cen-90":{"seq":36,"level":5,"module":"cen","term":"BankAssignedCreditorIdentifier","code":"BT-90"},
"cen-91":{"seq":37,"level":5,"module":"cen","term":"DebitedAccountIdentifier","code":"BT-91"},
"cenG-3":{"seq":38,"level":3,"module":"cen","term":"PRECEDING_INVOICE_REFERENCE","code":"BG-3"},
"tafG-1":{"seq":528,"level":4,"module":"taf","term":"originatingDocumentStructure","code":""},
"taf-4":{"seq":529,"level":5,"module":"taf","term":"originatingDocumentType","code":"","type":"Project Purchase order  Receiving advice Tender or lot"},
"taf-5":{"seq":530,"level":5,"module":"taf","term":"originatingDocumentNumber","code":"BT-25 BT-11 BT-13 BT-15 BT-17"},
"taf-6":{"seq":531,"level":5,"module":"taf","term":"originatingDocumentDate","code":"BT-26"},
"taf-5":{"seq":530,"level":5,"module":"taf","term":"originatingDocumentNumber","code":"BT-132"},
"cen-18":{"seq":288,"level":3,"module":"cen","term":"InvoicedObjectIdentifier","code":"BT-18"},
"cenG-1":{"seq":39,"level":3,"module":"cen","term":"INVOICE_NOTE","code":"BG-1"},
"cen-21":{"seq":40,"level":4,"module":"cen","term":"InvoiceNoteSubjectCode","code":"BT-21"},
"cor-7":{"seq":10,"level":3,"module":"cor","term":"entriesComment","code":"BT-22"},
"cenG-2":{"seq":42,"level":3,"module":"cen","term":"PROCESS_CONTROL","code":"BG-2"},
"cen-23":{"seq":43,"level":4,"module":"cen","term":"BusinessProcessType","code":"BT-23"},
"cen-24":{"seq":44,"level":4,"module":"cen","term":"SpecificationIdentifier","code":"BT-24"},
"taf-4":{"seq":529,"level":5,"module":"taf","term":"originatingDocumentType","code":"BT-133"},
"cenG-24":{"seq":280,"level":3,"module":"cen","term":"ADDITIONAL_SUPPORTING_DOCUMENTS","code":"BG-24"},
"cen-122":{"seq":281,"level":4,"module":"cen","term":"SupportingDocumentReference","code":"BT-122"},
"cen-123":{"seq":282,"level":4,"module":"cen","term":"SupportingDocumentDescription","code":"BT-123"},
"cen-124":{"seq":283,"level":4,"module":"cen","term":"ExternalDocumentLocation","code":"BT-124"},
"cen-125":{"seq":284,"level":4,"module":"cen","term":"AttachedDocument","code":"BT-125"},
"cen-125A":{"seq":285,"level":4,"module":"cen","term":"AttachedDocumentMimeCode","code":"BT-125A"},
"cen-125B":{"seq":286,"level":4,"module":"cen","term":"AttachedDocumentFilename","code":"BT-125B"},
"corG-3":{"seq":45,"level":2,"module":"cor","term":"entityInformation","code":""},
"corG-9":{"seq":142,"level":3,"module":"cor","term":"identifierReference","code":" BG-4 BG-11 BG-7 BG-10 BG-13"},
"cor-51":{"seq":153,"level":4,"module":"cor","term":"identifierType","code":"","type":"SELLER SELLER TAX REPRESENTATIVE PARTY BUYER PAYEE DELIVERY INFORMATION"},
"cor-44":{"seq":143,"level":4,"module":"cor","term":"identifierCode","code":" BT-29 BT-46 BT-60"},
"cor-45":{"seq":145,"level":4,"module":"cor","term":"identifierAuthorityCode","code":" BT-30 BT-47 BT-61"},
"cor-45":{"seq":145,"level":4,"module":"cor","term":"identifierAuthorityCode","code":" BT-31 BT-63 BT-48"},
"cor-45":{"seq":145,"level":4,"module":"cor","term":"identifierAuthorityCode","code":" BT-32"},
"cor-46":{"seq":146,"level":4,"module":"cor","term":"identifierAuthority","code":" BT-30A BT-47A BT-61A"},
"cor-50":{"seq":152,"level":4,"module":"cor","term":"identifierDescription","code":" BT-27 BT-62 BT-44 BT-59 BT-70"},
"cen-28":{"seq":150,"level":4,"module":"cen","term":"tradingName","code":" BT-28 BT-45"},
"cen-33":{"seq":151,"level":4,"module":"cen","term":"additionalLegalInformation","code":" BT-33"},
"busG-20":{"seq":165,"level":4,"module":"bus","term":"identifierAddress","code":" BG-5 BG-12 BG-8 BG-15"},
"bus-124":{"seq":169,"level":5,"module":"bus","term":"identifierStreet","code":" BT-35 BT-64 BT-50 BT-75"},
"bus-125":{"seq":170,"level":5,"module":"bus","term":"identifierAddressStreet2","code":" BT-36 BT-65 BT-51 BT-76"},
"cen-162":{"seq":171,"level":5,"module":"cen","term":"AddressLine3","code":" BT-162 BT-164 BT-163 BT-165"},
"bus-126":{"seq":172,"level":5,"module":"bus","term":"identifierCity","code":" BT-37 BT-66 BT-52 BT-77"},
"bus-127":{"seq":173,"level":5,"module":"bus","term":"identifierStateOrProvince","code":" BT-39 BT-68 BT-54 BT-79"},
"bus-128":{"seq":174,"level":5,"module":"bus","term":"identifierCountry","code":" BT-40 BT-69 BT-55 BT-80"},
"bus-129":{"seq":175,"level":5,"module":"bus","term":"identifierZipOrPostalCode","code":" BT-38 BT-67 BT-53 BT-78"},
"bus-129":{"seq":175,"level":5,"module":"bus","term":"identifierZipOrPostalCode","code":""},
"bus-130":{"seq":176,"level":5,"module":"bus","term":"identifierAddressLocationIdentifier","code":" BT-71"},
"corG-14":{"seq":177,"level":4,"module":"cor","term":"identifierContactInformationStructure","code":" BG-6 BG-9"},
"cor-63":{"seq":66,"level":5,"module":"cor","term":"identifierContactAttentionLine","code":" BT-41 BT-56"},
"cor-66":{"seq":67,"level":6,"module":"cor","term":"identifierContactPhoneNumber","code":" BT-42 BT-57"},
"cen-34":{"seq":68,"level":4,"module":"cen","term":"organizationAddressStreet3","code":" BT-34 BT-49"},
"cor-70":{"seq":69,"level":6,"module":"cor","term":"identifierContactEmailAddress","code":" BT-43 BT-58"},
"bus-35":{"seq":70,"level":6,"module":"bus","term":"contactAttentionLine","code":" BT-10"},
"busG-18":{"seq":197,"level":3,"module":"bus","term":"reportingCalendar","code":""},
"cenG-14":{"seq":206,"level":4,"module":"cen","term":"INVOICING_PERIOD","code":"BG-14"},
"cor-8":{"seq":11,"level":5,"module":"cor","term":"periodCoveredStart","code":"BT-73"},
"cor-9":{"seq":12,"level":5,"module":"cor","term":"periodCoveredEnd","code":"BT-74"},
"corG-4":{"seq":215,"level":2,"module":"cor","term":"entryHeader","code":""},
"cenG-20":{"seq":253,"level":3,"module":"cen","term":"DOCUMENT_LEVEL_ALLOWANCES","code":""},
"cor-40":{"seq":320,"level":4,"module":"cor","term":"amount","code":"BT-92"},
"cor-99":{"seq":508,"level":4,"module":"cor","term":"taxCode","code":"BT-95"},
"cor-98":{"seq":507,"level":4,"module":"cor","term":"taxPercentageRate","code":"BT-96"},
"cen-93":{"seq":254,"level":4,"module":"cen","term":"DocumentLevelAllowanceBaseAmount","code":"BT-93"},
"cen-94":{"seq":255,"level":4,"module":"cen","term":"DocumentLevelAllowancePercentage","code":"BT-94"},
"cen-97":{"seq":256,"level":4,"module":"cen","term":"DocumentLevelAllowanceReason","code":"BT-97"},
"cen-98":{"seq":257,"level":4,"module":"cen","term":"DocumentLevelAllowanceReasonCode","code":"BT-98"},
"cenG-21":{"seq":258,"level":3,"module":"cen","term":"DOCUMENT_LEVEL_CHARGES","code":""},
"cor-40":{"seq":320,"level":4,"module":"cor","term":"amount","code":"BT-99"},
"cor-99":{"seq":508,"level":4,"module":"cor","term":"taxCode","code":"BT-102"},
"cor-98":{"seq":507,"level":4,"module":"cor","term":"taxPercentageRate","code":"BT-103"},
"cen-100":{"seq":259,"level":4,"module":"cen","term":"DocumentLevelChargeBaseAmount","code":"BT-100"},
"cen-101":{"seq":260,"level":4,"module":"cen","term":"DocumentLevelChargePercentage","code":"BT-101"},
"cen-104":{"seq":261,"level":4,"module":"cen","term":"DocumentLevelChargeReason","code":"BT-104"},
"cen-105":{"seq":262,"level":4,"module":"cen","term":"DocumentLevelChargeReasonCode","code":"BT-105"},
"cenG-23":{"seq":273,"level":3,"module":"cen","term":"VAT_BREAKDOWN","code":"BG-23"},
"cen-116":{"seq":274,"level":4,"module":"cen","term":"VATCategoryTaxableAmount","code":"BT-116"},
"cen-117":{"seq":275,"level":4,"module":"cen","term":"VATCategoryTaxAmount","code":"BT-117"},
"cen-118":{"seq":276,"level":4,"module":"cen","term":"VATCategoryCode ","code":"BT-118"},
"cen-119":{"seq":277,"level":4,"module":"cen","term":"VATCategoryRate","code":"BT-119"},
"cen-120":{"seq":278,"level":4,"module":"cen","term":"VATExemptionReasonText","code":"BT-120"},
"cen-121":{"seq":279,"level":4,"module":"cen","term":"VATExemptionReasonCode","code":"BT-121"},
"cenG-22":{"seq":263,"level":3,"module":"cen","term":"DOCUMENT_TOTALS","code":"BG-22"},
"cen-106":{"seq":264,"level":4,"module":"cen","term":"SumOfInvoiceLineNetAmount","code":"BT-106"},
"cen-107":{"seq":265,"level":4,"module":"cen","term":"SumOfAllowancesOnDocumentLevel","code":"BT-107"},
"cen-108":{"seq":266,"level":4,"module":"cen","term":"SumOfChargesOnDocumentLevel","code":"BT-108"},
"cen-109":{"seq":267,"level":4,"module":"cen","term":"InvoiceTotalAmountWithoutVAT","code":"BT-109"},
"cen-111":{"seq":268,"level":4,"module":"cen","term":"InvoiceTotalVATAmountInAccountingCurrency","code":"BT-111"},
"cen-112":{"seq":269,"level":4,"module":"cen","term":"InvoiceTotalAmountWithVAT","code":"BT-112"},
"cen-113":{"seq":270,"level":4,"module":"cen","term":"PaidAmount","code":"BT-113"},
"cen-114":{"seq":271,"level":4,"module":"cen","term":"RoundingAmount","code":"BT-114"},
"cen-115":{"seq":272,"level":4,"module":"cen","term":"AmountDueForPayment","code":"BT-115"},
"corG-5":{"seq":289,"level":3,"module":"cor","term":"entryDetail","code":"BG-25"},
"cor-21":{"seq":290,"level":4,"module":"cor","term":"lineNumber","code":"BT-128"},
"cor-22":{"seq":291,"level":4,"module":"cor","term":"lineNumberCounter","code":"BT-126"},
"cor-23":{"seq":297,"level":4,"module":"cor","term":"accountMainID","code":"BT-19"},
"cen-131":{"seq":292,"level":4,"module":"cen","term":"InvoiceLineNetAmount","code":"BT-131"},
"cen-136":{"seq":341,"level":4,"module":"cen","term":"InvoiceLineAllowanceAmount","code":"BT-136"},
"cen-141":{"seq":347,"level":4,"module":"cen","term":"InvoiceLineChargeAmount","code":"BT-141"},
"bus-135":{"seq":380,"level":4,"module":"bus","term":"paymentMethod","code":"BT-81"},
"cor-85":{"seq":430,"level":4,"module":"cor","term":"detailComment","code":"BT-127"},
"cor-89":{"seq":434,"level":4,"module":"cor","term":"shipReceivedDate","code":"BT-72"},
"cor-90":{"seq":435,"level":4,"module":"cor","term":"maturityDate","code":"BT-9"},
"cor-91":{"seq":436,"level":4,"module":"cor","term":"terms","code":"BT-20"},
"busG-21":{"seq":437,"level":4,"module":"bus","term":"measurable","code":"BG-29"},
"cen-146":{"seq":483,"level":5,"module":"cen","term":"ItemNetPrice","code":"BT-146"},
"cen-147":{"seq":484,"level":5,"module":"cen","term":"ItemPriceDiscount","code":"BT-147"},
"cen-148":{"seq":485,"level":5,"module":"cen","term":"ItemGrossPrice","code":"BT-148"},
"bus-144":{"seq":446,"level":5,"module":"bus","term":"measurableQuantity","code":"BT-149"},
"bus-146":{"seq":451,"level":5,"module":"bus","term":"measurableUnitOfMeasure","code":"BT-150"},
"busG-21":{"seq":437,"level":4,"module":"bus","term":"measurable","code":"BG-31"},
"bus-143":{"seq":445,"level":5,"module":"bus","term":"measurableDescription","code":"BT-153"},
"cen-155":{"seq":448,"level":5,"module":"cen","term":"ItemSellersIdentifier","code":"BT-155"},
"cen-156":{"seq":449,"level":5,"module":"cen","term":"ItemBuyersIdentifier","code":"BT-156"},
"bus-139":{"seq":441,"level":5,"module":"bus","term":"measurableID","code":"BT-157"},
"bus-140":{"seq":442,"level":5,"module":"bus","term":"measurableIDSchema","code":"BT-157A"},
"bus-144":{"seq":446,"level":5,"module":"bus","term":"measurableQuantity","code":"BT-129"},
"bus-145":{"seq":447,"level":5,"module":"bus","term":"measurableQualifier","code":"BT-158"},
"cen-159":{"seq":450,"level":5,"module":"cen","term":"itemCountryOfOrigin","code":"BT-159"},
"bus-146":{"seq":451,"level":5,"module":"bus","term":"measurableUnitOfMeasure","code":"BT-130"},
"cenG-26":{"seq":293,"level":4,"module":"cen","term":"INVOICE_LINE_PERIOD","code":"BG-26"},
"bus-148":{"seq":453,"level":5,"module":"bus","term":"measurableStartDateTime","code":"BT-134"},
"bus-149":{"seq":454,"level":5,"module":"bus","term":"measurableEndDateTime","code":"BT-135"},
"corG-19":{"seq":500,"level":4,"module":"cor","term":"taxes","code":"BG-30"},
"cor-95":{"seq":504,"level":5,"module":"cor","term":"taxAmount","code":"BT-110"},
"cor-95":{"seq":504,"level":5,"module":"cor","term":"taxAmount","code":"BT-117"},
"cor-98":{"seq":507,"level":5,"module":"cor","term":"taxPercentageRate","code":"BT-119"},
"cor-98":{"seq":507,"level":5,"module":"cor","term":"taxPercentageRate","code":"BT-152"},
"cor-99":{"seq":508,"level":5,"module":"cor","term":"taxCode","code":"BT-118"},
"cor-99":{"seq":508,"level":5,"module":"cor","term":"taxCode","code":"BT-151"},
"muc-33":{"seq":511,"level":5,"module":"muc","term":"taxCurrency","code":"BT-6"},
"cenG-27":{"seq":340,"level":4,"module":"cen","term":"INVOICE_LINE_ALLOWANCES","code":"BG-27"},
"cen-137":{"seq":342,"level":5,"module":"cen","term":"InvoiceLineAllowanceBaseAmount","code":"BT-137"},
"cen-138":{"seq":343,"level":5,"module":"cen","term":"InvoiceLineAllowancePercentage","code":"BT-138"},
"cen-139":{"seq":344,"level":5,"module":"cen","term":"InvoiceLineAllowanceReason","code":"BT-139"},
"cen-140":{"seq":345,"level":5,"module":"cen","term":"InvoiceLineAllowanceReasonCode","code":"BT-140"},
"cenG-28":{"seq":346,"level":4,"module":"cen","term":"INVOICE_LINE_CHARGES","code":"BG-28"},
"cen-142":{"seq":348,"level":5,"module":"cen","term":"InvoiceLineChargeBaseAmount","code":"BT-142"},
"cen-143":{"seq":349,"level":5,"module":"cen","term":"InvoiceLineChargePercentage","code":"BT-143"},
"cen-144":{"seq":350,"level":5,"module":"cen","term":"InvoiceLineChargeReason","code":"BT-144"},
"cen-145":{"seq":351,"level":5,"module":"cen","term":"InvoiceLineChargeReasonCode","code":"BT-145"},
"cen-154":{"seq":352,"level":5,"module":"cen","term":"ItemDescription","code":"BT-154"},
"cenG-32":{"seq":480,"level":4,"module":"cen","term":"ITEM_ATTRIBUTES","code":"BG-32"},
"cen-160":{"seq":481,"level":5,"module":"cen","term":"ItemAttributeName","code":"BT-160"},
"cen-161":{"seq":482,"level":5,"module":"cen","term":"ItemAttributeValue","code":"BT-161"}};
