xbrl_gl={
    "corG-1":[{ "name":"accountingEntries",
        "code":"",
        "corG-2":[{ "name":"documentInfo",
            "code":"",
            "cor-76":[{ "name":"documentNumber",
                "code":"BT-1" }],
            "cor-79":[{ "name":"documentDate",
                "code":"BT-2" }],
            "cor-73":[{ "name":"documentType",
                "code":"BT-3" }],
            "muc-4":[{ "name":"amountOriginalCurrency",
                "code":"BT-5" }],
            "cor-43":[{ "name":"postingDate",
                "code":"BT-7" }],
            "cen-8":[{ "name":"ValueAddedTaxPointDateCode",
                "code":"BT-8" }],
            "cenG-16":[{ "name":"PAYMENT_INSTRUCTIONS",
                "code":"BG-16",
                "cen-82":[{ "name":"PaymentMeansText",
                    "code":"BT-82" }],
                "cen-83":[{ "name":"RemittanceInformation",
                    "code":"BT-83" }],
                "cenG-17":[{ "name":"CREDIT_TRANSFER",
                    "code":"BG-17",
                    "cen-84":[{ "name":"PaymentAccountIdentifier",
                        "code":"BT-84" }],
                    "cen-85":[{ "name":"PaymentAccountName",
                        "code":"BT-85" }],
                    "cen-86":[{ "name":"PaymentServiceProviderIdentifier",
                        "code":"BT-86" }]
                }],
                "cenG-18":[{ "name":"PAYMENT_CARD_INFORMATION",
                    "code":"BG-18",
                    "cen-87":[{ "name":"PaymentCardPrimaryAccountNumber",
                        "code":"BT-87" }],
                    "cen-88":[{ "name":"PaymentCardHolderName",
                        "code":"BT-88" }]
                }],
                "cenG-19":[{ "name":"DIRECT_DEBIT",
                    "code":"BG-19",
                    "cen-89":[{ "name":"MandateReferenceIdentifier",
                        "code":"BT-89" }],
                    "cen-90":[{ "name":"BankAssignedCreditorIdentifier",
                        "code":"BT-90" }],
                    "cen-91":[{ "name":"DebitedAccountIdentifier",
                        "code":"BT-91" }]
                }]
            }],
            "cenG-3":[{ "name":"PRECEDING_INVOICE_REFERENCE",
                "code":"BG-3",
                "tafG-1":[{ "name":"originatingDocumentStructure",
                    "code":"",
                    "taf-4":[{ "name":"originatingDocumentType",
                        "code":" Project Purchase order  Receiving advice Tender or lot" }],
                    "taf-5":[{ "name":"originatingDocumentNumber",
                        "code":"BT-25 BT-11 BT-13 BT-15 BT-17" }],
                    "taf-6":[{ "name":"originatingDocumentDate",
                        "code":"BT-26" }],
                    "taf-5":[{ "name":"originatingDocumentNumber",
                        "code":"BT-132" }]
                }]
            }],
            "cen-18":[{ "name":"InvoicedObjectIdentifier",
                "code":"BT-18" }],
            "cenG-1":[{ "name":"INVOICE_NOTE",
                "code":"BG-1",
                "cen-21":[{ "name":"InvoiceNoteSubjectCode",
                    "code":"BT-21" }]
            }],
            "cor-7":[{ "name":"entriesComment",
                "code":"BT-22" }],
            "cenG-2":[{ "name":"PROCESS_CONTROL",
                "code":"BG-2",
                "cen-23":[{ "name":"BusinessProcessType",
                    "code":"BT-23" }],
                "cen-24":[{ "name":"SpecificationIdentifier",
                    "code":"BT-24",
                    "taf-4":[{ "name":"originatingDocumentType",
                        "code":"BT-133" }]
                }]
            }],
            "cenG-24":[{ "name":"ADDITIONAL_SUPPORTING_DOCUMENTS",
                "code":"BG-24",
                "cen-122":[{ "name":"SupportingDocumentReference",
                    "code":"BT-122" }],
                "cen-123":[{ "name":"SupportingDocumentDescription",
                    "code":"BT-123" }],
                "cen-124":[{ "name":"ExternalDocumentLocation",
                    "code":"BT-124" }],
                "cen-125":[{ "name":"AttachedDocument",
                    "code":"BT-125" }],
                "cen-125A":[{ "name":"AttachedDocumentMimeCode",
                    "code":"BT-125A" }],
                "cen-125B":[{ "name":"AttachedDocumentFilename",
                    "code":"BT-125B" }]
            }]
        }],
        "corG-3":[{ "name":"entityInformation",
            "code":"",
            "corG-9":[{ "name":"identifierReference",
                "code":" BG-4 BG-11 BG-7 BG-10 BG-13",
                "cor-51":[{ "name":"identifierType",
                    "code":" SELLER SELLER TAX REPRESENTATIVE PARTY BUYER PAYEE DELIVERY INFORMATION" }],
                "cor-44":[{ "name":"identifierCode",
                    "code":" BT-29 BT-46 BT-60" }],
                "cor-45":[{ "name":"identifierAuthorityCode",
                    "code":" BT-30 BT-47 BT-61 BT-31 BT-63 BT-48 BT-32" }],
                "cor-46":[{ "name":"identifierAuthority",
                    "code":" BT-30A BT-47A BT-61A" }],
                "cor-50":[{ "name":"identifierDescription",
                    "code":" BT-27 BT-62 BT-44 BT-59 BT-70" }],
                "cen-28":[{ "name":"tradingName",
                    "code":" BT-28 BT-45" }],
                "cen-33":[{ "name":"additionalLegalInformation",
                    "code":" BT-33" }],
                "busG-20":[{ "name":"identifierAddress",
                    "code":" BG-5 BG-12 BG-8 BG-15",
                    "bus-124":[{ "name":"identifierStreet",
                        "code":" BT-35 BT-64 BT-50 BT-75" }],
                    "bus-125":[{ "name":"identifierAddressStreet2",
                        "code":" BT-36 BT-65 BT-51 BT-76" }],
                    "cen-162":[{ "name":"AddressLine3",
                        "code":" BT-162 BT-164 BT-163 BT-165" }],
                    "bus-126":[{ "name":"identifierCity",
                        "code":" BT-37 BT-66 BT-52 BT-77"  }],
                    "bus-127":[{ "name":"identifierStateOrProvince",
                        "code":" BT-39 BT-68 BT-54 BT-79" }],
                    "bus-128":[{ "name":"identifierCountry",
                        "code":" BT-40 BT-69 BT-55 BT-80" }],
                    "bus-129":[{ "name":"identifierZipOrPostalCode",
                        "code":" BT-38 BT-67 BT-53 BT-78" }],
                    "bus-130":[{ "name":"identifierAddressLocationIdentifier",
                        "code":" BT-71" }]
                }],
                "corG-14":[{ "name":"identifierContactInformationStructure",
                    "code":" BG-6 BG-9",
                    "cor-63":[{ "name":"identifierContactAttentionLine",
                        "code":" BT-41 BT-56",
                        "cor-66":[{ "name":"identifierContactPhoneNumber",
                            "code":" BT-42 BT-57" }]
                    }]
                }],
                "cen-34":[{ "name":"organizationAddressStreet3", // check here
                    "code":" BT-34 BT-49",
                    "cor-63":[{ "cor-70":[{ "name":"identifierContactEmailAddress",
                            "code":" BT-43 BT-58" }],
                        "bus-35":[{ "name":"contactAttentionLine",
                            "code":" BT-10" }]
                    }]
                }]
            }],
            "busG-18":[{ "name":"reportingCalendar",
                "code":"",
                "cenG-14":[{ "name":"INVOICING_PERIOD",
                    "code":"BG-14",
                    "cor-8":[{ "name":"periodCoveredStart",
                        "code":"BT-73" }],
                    "cor-9":[{ "name":"periodCoveredEnd",
                        "code":"BT-74" }]
                }]
            }]
        }],
        "corG-4":[{
            "name":"entryHeader",
            "code":"",
            "cenG-20":[{ "name":"DOCUMENT_LEVEL_ALLOWANCES",
                "code":"",
                "cor-40":[{ "name":"amount",
                    "code":"BT-92" }],
                "cor-99":[{ "name":"taxCode",
                    "code":"BT-95" }],
                "cor-98":[{ "name":"taxPercentageRate",
                    "code":"BT-96" }],
                "cen-93":[{ "name":"DocumentLevelAllowanceBaseAmount",
                    "code":"BT-93" }],
                "cen-94":[{ "name":"DocumentLevelAllowancePercentage",
                    "code":"BT-94" }],
                "cen-97":[{ "name":"DocumentLevelAllowanceReason",
                    "code":"BT-97" }],
                "cen-98":[{ "name":"DocumentLevelAllowanceReasonCode",
                    "code":"BT-98" }]
            }],
            "cenG-21":[{
                "name":"DOCUMENT_LEVEL_CHARGES",
                "code":"",
                "cor-40":[{ "name":"amount",
                    "code":"BT-99" }],
                "cor-99":[{ "name":"taxCode",
                    "code":"BT-102" }],
                "cor-98":[{ "name":"taxPercentageRate",
                    "code":"BT-103" }],
                "cen-100":[{ "name":"DocumentLevelChargeBaseAmount",
                    "code":"BT-100" }],
                "cen-101":[{ "name":"DocumentLevelChargePercentage",
                    "code":"BT-101" }],
                "cen-104":[{ "name":"DocumentLevelChargeReason",
                    "code":"BT-104" }],
                "cen-105":[{ "name":"DocumentLevelChargeReasonCode",
                    "code":"BT-105" }]
            }],
            "cenG-23":[{ "name":"VAT_BREAKDOWN",
                "code":"BG-23",
                "cen-116":[{ "name":"VATCategoryTaxableAmount",
                    "code":"BT-116" }],
                "cen-117":[{ "name":"VATCategoryTaxAmount",
                    "code":"BT-117" }],
                "cen-118":[{ "name":"VATCategoryCode ",
                    "code":"BT-118" }],
                "cen-119":[{ "name":"VATCategoryRate",
                    "code":"BT-119" }],
                "cen-120":[{ "name":"VATExemptionReasonText",
                    "code":"BT-120" }],
                "cen-121":[{ "name":"VATExemptionReasonCode",
                    "code":"BT-121" }]
            }],
            "cenG-22":[{ "name":"DOCUMENT_TOTALS",
                "code":"BG-22",
                "cen-106":[{ "name":"SumOfInvoiceLineNetAmount",
                    "code":"BT-106" }],
                "cen-107":[{ "name":"SumOfAllowancesOnDocumentLevel",
                    "code":"BT-107" }],
                "cen-108":[{ "name":"SumOfChargesOnDocumentLevel",
                    "code":"BT-108" }],
                "cen-109":[{ "name":"InvoiceTotalAmountWithoutVAT",
                    "code":"BT-109" }],
                "cen-111":[{ "name":"InvoiceTotalVATAmountInAccountingCurrency",
                    "code":"BT-111" }],
                "cen-112":[{ "name":"InvoiceTotalAmountWithVAT",
                    "code":"BT-112" }],
                "cen-113":[{ "name":"PaidAmount",
                    "code":"BT-113" }],
                "cen-114":[{ "name":"RoundingAmount",
                    "code":"BT-114" }],
                "cen-115":[{ "name":"AmountDueForPayment",
                    "code":"BT-115" }]
            }],
            "corG-5":[{ "name":"entryDetail",
                "code":"BG-25",
                "cor-21":[{ "name":"lineNumber",
                    "code":"BT-128" }],
                "cor-22":[{ "name":"lineNumberCounter",
                    "code":"BT-126" }],
                "cor-23":[{ "name":"accountMainID",
                    "code":"BT-19" }],
                "cen-131":[{ "name":"InvoiceLineNetAmount",
                    "code":"BT-131" }],
                "cen-136":[{ "name":"InvoiceLineAllowanceAmount",
                    "code":"BT-136" }],
                "cen-141":[{ "name":"InvoiceLineChargeAmount",
                    "code":"BT-141" }],
                "bus-135":[{ "name":"paymentMethod",
                    "code":"BT-81" }],
                "cor-85":[{ "name":"detailComment",
                    "code":"BT-127" }],
                "cor-89":[{ "name":"shipReceivedDate",
                    "code":"BT-72" }],
                "cor-90":[{ "name":"maturityDate",
                    "code":"BT-9" }],
                "cor-91":[{ "name":"terms",
                    "code":"BT-20" }],
                "busG-21":[{ "name":"measurable",
                    "code":"BG-29",
                    "cen-146":[{ "name":"ItemNetPrice",
                        "code":"BT-146" }],
                    "cen-147":[{ "name":"ItemPriceDiscount",
                        "code":"BT-147" }],
                    "cen-148":[{ "name":"ItemGrossPrice",
                        "code":"BT-148" }],
                    "bus-144":[{ "name":"measurableQuantity",
                        "code":"BT-149" }],
                    "bus-146":[{ "name":"measurableUnitOfMeasure",
                        "code":"BT-150" }]
                },
                { "name":"measurable",
                    "code":"BG-31",
                    "bus-143":[{ "name":"measurableDescription",
                    "code":"BT-153" }],
                    "cen-155":[{ "name":"ItemSellersIdentifier",
                        "code":"BT-155" }],
                    "cen-156":[{ "name":"ItemBuyersIdentifier",
                        "code":"BT-156" }],
                    "bus-139":[{ "name":"measurableID",
                        "code":"BT-157" }],
                    "bus-140":[{ "name":"measurableIDSchema",
                        "code":"BT-157A" }],
                    "bus-144":[{ "name":"measurableQuantity",
                        "code":"BT-129" }],
                    "bus-145":[{ "name":"measurableQualifier",
                        "code":"BT-158" }],
                    "cen-159":[{ "name":"itemCountryOfOrigin",
                    "code":"BT-159" }],
                    "bus-146":[{ "name":"measurableUnitOfMeasure",
                        "code":"BT-130" }]
                }],
                "cenG-26":[{ "name":"INVOICE_LINE_PERIOD",
                    "code":"BG-26",
                    "bus-148":[{ "name":"measurableStartDateTime",
                        "code":"BT-134" }],
                    "bus-149":[{ "name":"measurableEndDateTime",
                        "code":"BT-135" }]
                }],
                "corG-19":[{ "name":"taxes",
                    "code":"BG-30",
                    "cor-95":[{ "name":"taxAmount",
                        "code":"BT-110 BT-117" }],
                    "cor-98":[{ "name":"taxPercentageRate",
                        "code":"BT-119 BT-152" }],
                    "cor-99":[{ "name":"taxCode",
                        "code":"BT-118 BT-151" }],
                    "muc-33":[{ "name":"taxCurrency",
                        "code":"BT-6" }]
                }],
                "cenG-27":[{ "name":"INVOICE_LINE_ALLOWANCES",
                    "code":"BG-27",
                    "cen-137":[{ "name":"InvoiceLineAllowanceBaseAmount",
                        "code":"BT-137" }],
                    "cen-138":[{ "name":"InvoiceLineAllowancePercentage",
                        "code":"BT-138" }],
                    "cen-139":[{ "name":"InvoiceLineAllowanceReason",
                        "code":"BT-139" }],
                    "cen-140":[{ "name":"InvoiceLineAllowanceReasonCode",
                        "code":"BT-140" }]
                }],
                "cenG-28":[{ "name":"INVOICE_LINE_CHARGES",
                    "code":"BG-28",
                    "cen-142":[{ "name":"InvoiceLineChargeBaseAmount",
                        "code":"BT-142" }],
                    "cen-143":[{ "name":"InvoiceLineChargePercentage",
                        "code":"BT-143" }],
                    "cen-144":[{ "name":"InvoiceLineChargeReason",
                        "code":"BT-144" }],
                    "cen-145":[{ "name":"InvoiceLineChargeReasonCode",
                        "code":"BT-145" }],
                    "cen-154":[{ "name":"ItemDescription",
                        "code":"BT-154" }]
                }],
                "cenG-32":[{ "name":"ITEM_ATTRIBUTES",
                    "code":"BG-32",
                    "cen-160":[{ "name":"ItemAttributeName",
                        "code":"BT-160" }],
                    "cen-161":[{ "name":"ItemAttributeValue",
                        "code":"BT-161" }]
                }]
            }]
        }]
    }]
};

var initModule = function() {
    console.log(xbrl_gl)
}