#!/usr/bin/env python3
#coding: utf-8
#
# generate html <table> fron CSV file
# 
# designed by SAMBUICHI, Nobuyuki (Sambuichi Professional Engineers Office)
# written by SAMBUICHI, Nobuyuki (Sambuichi Professional Engineers Office)
#
# MIT License
# 
# Copyright (c) 2021 SAMBUICHI Nobuyuki (Sambuichi Professional Engineers Office)
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# import xml.etree.ElementTree as ET
# from collections import defaultdict
import csv
import sys 
import os
import argparse
import codecs

def file_path(pathname):
  if '/' == pathname[0:1]:
    return pathname
  else:
    dir = os.path.dirname(__file__)
    new_path = os.path.join(dir, pathname)
    return new_path

if __name__ == '__main__':
  # Create the parser
  parser = argparse.ArgumentParser(prog='csv2html',
                                  usage='%(prog)s [options] infile -o outfile',
                                  description='CSVファイルからhtmlの<table>を作成')
  # Add the arguments
  parser.add_argument('inFile', metavar='infile', type=str, help='入力CSVファイル')
  parser.add_argument('-o', '--out')
  parser.add_argument('-e', '--encoding')  # 'Shift_JIS' 'cp932'
  parser.add_argument('-v', '--verbose', action='store_true')
  parser.add_argument('-d', '--debug', action='store_true')

  args = parser.parse_args()
  in_file = file_path(args.inFile)
  if args.out:
    out_file = args.out.lstrip()
    out_file = file_path(out_file)
  else:
    pre, ext = os.path.splitext(in_file)
    out_file = pre+'.html'
  ncdng = args.encoding
  if not ncdng:
    ncdng = 'UTF-8'
  else:
    ncdng = ncdng.lstrip()
  VERBOSE = args.verbose
  DEBUG = args.debug

  # Check if infile exists
  if not os.path.isfile(in_file):
    print('入力ファイルがありません')
    sys.exit()
  if VERBOSE:
    print('** START ** ', __file__)
    print(f'*** Input file {in_file}')

  with open(in_file,'r',encoding=ncdng,newline='') as f:
    reader = csv.reader(f)#, delimiter='\t')
    rows = []
    i = 0
    for row in reader:
      rows.append(row)

  with open(out_file,'w') as f:
    f.write('''
<!DOCTYPE html>
<head>
  <title>Japanese PEPPOL BIS Invoice Convert</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="icon" href="https://www.wuwei.space/jp_pint/billing-japan/favicon.ico">
</head>
<body>
    ''')
    f.write('<table>')
    for row in rows:
      if 'ibg'==row[0][:3]:
        f.write('<tr style="background:#e0f0f0">')
      else:
        f.write('<tr>')
      for cell in row:
        if cell:
          f.write(f'<td>{cell}</td>')
        else:
          if 'ibg'==row[0][:3]:
            f.write(f'<td>{cell}</td>')
          else:
            f.write(f'<td style="background:#d0d0d0">{cell}</td>')
      f.write('</tr>\n')
    f.write('''
    </table>
  </body>
</html>
    ''')

  if VERBOSE:
    print(f'** END ** {out_file}')